"""empty message

Revision ID: 174a0481ae48
Revises: 142fd6473fe2
Create Date: 2023-02-04 19:29:16.443405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174a0481ae48'
down_revision = '142fd6473fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asilo', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asilo', 'usuario', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asilo', type_='foreignkey')
    op.drop_column('asilo', 'id_usuario')
    # ### end Alembic commands ###
