"""empty message

Revision ID: 25244107e0ec
Revises: 65d62b661617
Create Date: 2023-01-18 12:48:58.592782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25244107e0ec'
down_revision = '65d62b661617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('login_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'login_step')
    # ### end Alembic commands ###
