"""empty message

Revision ID: 25d907304f23
Revises: 267460b0c54e
Create Date: 2023-04-22 14:20:50.835985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d907304f23'
down_revision = '267460b0c54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pix', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pix')
    # ### end Alembic commands ###
