"""empty message

Revision ID: 267460b0c54e
Revises: bc93ad6c2e7f
Create Date: 2023-02-05 23:02:36.973284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267460b0c54e'
down_revision = 'bc93ad6c2e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asilo', 'cep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asilo', sa.Column('cep', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
