"""empty message

Revision ID: 26c8f031f541
Revises: ee946a543104
Create Date: 2022-12-08 10:29:58.855716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c8f031f541'
down_revision = 'ee946a543104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nome', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
