"""empty message

Revision ID: 5c43a3d6569e
Revises: 25244107e0ec
Create Date: 2023-01-26 12:33:41.103750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c43a3d6569e'
down_revision = '25244107e0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'voluntario', ['id_usuario'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voluntario', type_='unique')
    # ### end Alembic commands ###
