"""empty message

Revision ID: 6b9d68e43ab9
Revises: dacce8dd4a33
Create Date: 2023-04-25 21:14:58.187558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9d68e43ab9'
down_revision = 'dacce8dd4a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asilo', sa.Column('pix', sa.String(length=100), nullable=True))
    op.add_column('asilo', sa.Column('cep', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asilo', 'cep')
    op.drop_column('asilo', 'pix')
    # ### end Alembic commands ###
