"""empty message

Revision ID: 6d218de2b130
Revises: 5b4421524cd5
Create Date: 2023-02-05 21:13:44.912702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d218de2b130'
down_revision = '5b4421524cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asilo', 'cep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asilo', sa.Column('cep', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
