"""empty message

Revision ID: 92ffc59045b9
Revises: eafcc2dd03e7
Create Date: 2023-02-04 18:55:46.036480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ffc59045b9'
down_revision = 'eafcc2dd03e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'visita', 'usuario', ['id_usuario'], ['id'])
    op.create_unique_constraint(None, 'voluntario', ['id_usuario'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voluntario', type_='unique')
    op.drop_constraint(None, 'visita', type_='foreignkey')
    # ### end Alembic commands ###
