"""empty message

Revision ID: bc93ad6c2e7f
Revises: 6d218de2b130
Create Date: 2023-02-05 22:08:06.761402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc93ad6c2e7f'
down_revision = '6d218de2b130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asilo', 'cep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asilo', sa.Column('cep', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
