"""empty message

Revision ID: bed1587b5d90
Revises: 
Create Date: 2023-12-07 18:16:34.449005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed1587b5d90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('larNome', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=2), nullable=True),
    sa.Column('nomeDoador', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.Enum('L', 'V', name='usertype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lar_de_idosos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('pix', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=100), nullable=True),
    sa.Column('principais_necessidades', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('voluntario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_voluntario', sa.Integer(), nullable=True),
    sa.Column('id_lar', sa.Integer(), nullable=True),
    sa.Column('dt_hr', sa.DateTime(), nullable=True),
    sa.Column('qnt_pessoas', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_lar'], ['lar_de_idosos.id'], ),
    sa.ForeignKeyConstraint(['id_voluntario'], ['voluntario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita')
    op.drop_table('voluntario')
    op.drop_table('lar_de_idosos')
    op.drop_table('usuario')
    op.drop_table('doacao')
    # ### end Alembic commands ###
