"""empty message

Revision ID: dacce8dd4a33
Revises: 
Create Date: 2023-04-25 19:15:14.578919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacce8dd4a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asiloName', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=2), nullable=True),
    sa.Column('nomeDoador', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.Enum('A', 'V', name='usertype'), nullable=True),
    sa.Column('login_step', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asilo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('voluntario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_asilo', sa.Integer(), nullable=True),
    sa.Column('nome_voluntario', sa.String(length=100), nullable=True),
    sa.Column('nome_asilo', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_asilo'], ['asilo.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita')
    op.drop_table('voluntario')
    op.drop_table('asilo')
    op.drop_table('usuario')
    op.drop_table('doacao')
    # ### end Alembic commands ###
