"""empty message

Revision ID: eafcc2dd03e7
Revises: 5c43a3d6569e
Create Date: 2023-02-04 18:50:22.623712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafcc2dd03e7'
down_revision = '5c43a3d6569e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visita', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visita', 'usuario', ['id_usuario'], ['id'])
    op.create_unique_constraint(None, 'voluntario', ['id_usuario'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voluntario', type_='unique')
    op.drop_constraint(None, 'visita', type_='foreignkey')
    op.drop_column('visita', 'id_usuario')
    # ### end Alembic commands ###
