"""migração inicial :ok_hand:

Revision ID: eb8c68c58be2
Revises: 
Create Date: 2022-08-29 14:14:12.629596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8c68c58be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asiloName', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=2), nullable=True),
    sa.Column('nomeDoador', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('doacao')
    # ### end Alembic commands ###
