"""adicionando mudanças da tabela usuario

Revision ID: ee946a543104
Revises: eb8c68c58be2
Create Date: 2022-12-06 18:00:53.554525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee946a543104'
down_revision = 'eb8c68c58be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('user_type', sa.Enum('ASILO', 'VOLUNTARIO', name='usertype'), nullable=True))
    op.add_column('usuario', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'admin')
    op.drop_column('usuario', 'user_type')
    # ### end Alembic commands ###
