"""empty message

Revision ID: ff714c6df160
Revises: 25d907304f23
Create Date: 2023-04-22 14:22:55.396712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff714c6df160'
down_revision = '25d907304f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asilo', sa.Column('pix', sa.String(length=100), nullable=True))
    op.drop_column('usuario', 'pix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pix', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('asilo', 'pix')
    # ### end Alembic commands ###
